# AppVeyor build configuration
#
# doc: http://www.appveyor.com/docs/build-configuration
# Qt-versions: https://www.appveyor.com/docs/build-environment/#qt
# validator: https://ci.appveyor.com/tools/validate-yaml

skip_tags: true
image:
  - macos
  - Ubuntu
  - Visual Studio 2015

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFM0NqOhTDfGjsA/+yXFeDN+d6w3W5Y5LxQriZysUgu1ftXx+q9sLFpGE8d5vIQ6e/Tcl1vGh3avj/JyGzqsYRBoHiUaUq09Azzz6uYf/fzkbpCh2qo4Ly47hssyimqWdO6LgXX90ImqBiukrOz/Vh2xUyy5xxrb5lR8uYbj/YSPuOaIW4b0XVcozN+pkjvex0g+53NuhcwI6sxfqI85Iy0AU0b03meYH9m9kPc+/p6GzuO+qR8bDVohtc5Yb845aPVXWwKCdn7eWnz90WlI1sdd5oWy9fCt08x3tWbdaR3BZKcGcu0qRhJSllGSmfmp63awLfqHLjDRHI4ImOloC5Ze+OIO0BA65BYTauUr6Szhk5UhhoE3cyVxzw9tfLBzfFP/1/ZkByyhNRtSdmw4OqTShNlfyeqWhyBQqlw3zvo1SOHi6YZi+S4ZddFG+C+OMgXqAZKwKubJpyBmm3C4asexz5PLwYcrzYozTTwjmLvS5KhQk9ogfvtV2cPyaHH0c= evpo@tw
    #  APPVEYOR_SSH_BLOCK: true

for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  environment:
    qtdir: "C:\\Qt\\latest\\mingw73_32"
    gpp: win32-g++

  install:
    - ps: |
        $path = [Environment]::GetEnvironmentVariable("path", "machine")
        $newPath = ($path.Split(';') | Where-Object { $_ -eq 'C:\ProgramData\chocolatey\bin' }) -join ';'
        [Environment]::SetEnvironmentVariable("path", $newPath, "machine")

    - cmd: |
        appveyor-retry choco install gpg4win
        set QTDIR=%qtdir%
        set QTTOOLS=C:\Qt\Tools\mingw730_32
        set GPGPATH="C:\Program Files (x86)\Gpg4win\..\GnuPG"
        set PATH=%GPGPATH%\bin;%QTTOOLS%\bin;%QTDIR%\bin;%PATH%;C:\MinGW\bin

  build_script:
    - cmd: |
        echo %PATH%
        dir C:\Qt
        dir C:\Qt\Tools
        dir C:\Qt\latest
        dir %GPGPATH%
        which g++
        g++ --version
        uname
        gpg --version
        python configure.py --debug-mode
        mingw32-make -j 1
        python configure.py --without-qt-ui --debug-mode --test
        mingw32-make -j 1
        bash scripts\tool.sh --run-tests
        bash scripts\tool.sh --run-func-tests --debug

-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sh: |
        sudo apt-get update
        sudo apt-get install --yes libbotan-2-dev mesa-common-dev libgl1-mesa-dev gnupg2

  build_script:
    - sh: |
        export PATH=${HOME}/Qt/5.12.10/gcc_64/bin:${PATH}
        qmake --version
        which g++
        g++ --version
        ./configure.py --debug-mode
        make -j 1
        ./configure.py --without-qt-ui --debug-mode --test
        make -j 1
        scripts/tool.sh --run-tests
        scripts/tool.sh --run-func-tests --debug

-
  matrix:
    only:
      - image: macos

  install:
    - sh: |
        echo "install in macos"

  build_script:
    - sh: |
        export QTDIR=${HOME}/Qt/5.15.2/clang_64
        export PATH=${QTDIR}/bin:${PATH}
        qmake --version
        ./configure.py --ldflags "-mmacosx-version-min=11.0" --cxxflags "-mmacosx-version-min=11.0"
        make
        ./configure.py --without-qt-ui --debug-mode --test --ldflags "-mmacosx-version-min=11.0" --cxxflags "-mmacosx-version-min=11.0"
        make
        scripts/tool.sh --run-tests
        scripts/tool.sh --run-func-tests --debug

# init:
#   - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

